### ISSUE TITLE
Benchmarks, e.g. Fig2 of Kraskov et al. 2004

### ISSUE THREAD

**Issue by guagualuo** [mutualinfo/mutual_info#2]
Hi Cottrell,

I recently started to explore the existing implementation of mutual information estimation. I have seen that you are also using these algorithms. 

Apparently there is a simple implementation of Kraskov2004 eq(8) in sklearn at https://github.com/scikit-learn/scikit-learn/blob/7e1e6d09bcc2eaeba98f7e737aac2ac782f0e5f1/sklearn/feature_selection/_mutual_info.py for 2 1-D variables, which I believe can be easily modified to higher dimensional variables. 

By testing basically the setup of two correlated normal distributed variables as in Fig.2, it seems to give the correct answer as far as N is large. However, it seems to be much worse in convergence compared to what is said in Fig.2: "Error bars are smaller than the sizes of the symbols" according to them. For sklearn implementation N=100, 1000, the error varies a lot. 

I am wondering if you have done this kind of benchmark for your implementation or other implementations? How's the convergence?

Cheers,

**Comment by cottrell** [comment]
I feel like I must have looked at it but have no record of that in my notes ... I had some brief post here https://github.com/scikit-learn/scikit-learn/issues/16188 a while back. 

The more I think about it, I feel like I started the process by using sklearn version but then hit "some issue" with it. I think a lot of these fail the invariance tests (invariant to monotonic transformations). I haven't thought about this for a while so the details are not in my head right now.
